### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by Defcon0** [contao-community-alliance/composer-plugin#55]
Hello folks,

due to a penetration test on one of our websites we now must restrict internet access for the web server to addresses on a whitelist. For http everything works fine, just https won't work. When updating packages, I get the following error:

> Loading composer repositories with package information
> The "https://legacy-packages-via.contao-community-alliance.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
> error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
> Failed to enable crypto
> failed to open stream: operation failed
> https://legacy-packages-via.contao-community-alliance.org could not be fully loaded, package information was loaded from the local cache and may be out of date
> The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
> error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
> Failed to enable crypto
> failed to open stream: operation failed
> https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

Now the responsible hoster says, we must pass the -k parameter to every curl call. The equivalent in php curl should be `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE)`. So I inserted this in src/Downloader.php with no success. This seems not to be the file which does the calls.

I also tried to pass the certificate by adding `curl_setopt($ch, CURLOPT_CAINFO, __DIR__ . "/certs/cacert.pem");` also with no success.

Is this an issue?

**Comment by discordier** [comment]
First off, no administrator in their right minds would suggest to disable peer verification as when you do so, you could skip ssl entirely as you have no idea who the called party is. See [curl](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html) documentation for this flag.

We are only setting this flag on systems where SNI is not available (see contao-community-alliance/composer-client source for details).

However, this is the composer-plugin, which is responsible for installing extensions, not downloading.
Downloading is done by composer itself (see the composer.phar in your contao installation in the directory TL_ROOT/composer).
There is nothing we can do in there.
As it seems, you have either a hopeless outdated server infrastructure (in the meaning that either openssl or curl do not speak SNI) or your certificate bundle is outdated (does not include current root certificates) or there is some misconfiguration on the server.
This issue is hard to detect without further information of the system like version strings of used components like openssl and curl and php and so on.

In general, this is not an issue of the plugin at all and neither of the composer-client but only in composer. The only reason why I do not send you over to the composer tracker is, that they do not officially support running composer from web but only from console.
Therefore this is the first thing I'd try on your side. Run composer from the composer directory via ssh and check if it works.

**Comment by Defcon0** [comment]
Big thanks for clarification. I also thought, this behavior of the hoster is quite suspect. I'll complain about that on monday. I think, the problem is that the communication is done by some proxy and therefore they needed some self signed certificate.

Anyway now I see, that this rather belongs to composer itself.
