### ISSUE TITLE
[2.4] Plugin should be working on both, composer update and composer install

### ISSUE THREAD

**Issue by Toflar** [contao-community-alliance/composer-plugin#61]
I need @discordier's help here because I'm not really familiar with the plugin. My issue is regarding the cloud (but not limited to it). Basically whenever you upload a `composer.lock` file you resolved elsewhere (e.g. also locally), it writes e.g. `tcpdf` etc. into the `composer.lock` file. Imho the plugin should also activate itself when I then run a `composer install` on the target system so it ignores the stuff already provided by Contao (or of course `contao/core` itself).

**Comment by aschempp** [comment]
I wonder why the "disallowed" packages are still added to the `composer.lock`, and if this is also the case for v3?

**Comment by Toflar** [comment]
Because I did not execute any pre update events.

**Comment by discordier** [comment]
The plugin can not ignore them as it has nothing to do with the installation itself (aside from symlinking stuff).
Your problem is already in the solver phase, which the plugin does not interfere with (aside from injecting the installed contao version which you do not have in the cloud based solving).

After discussion on mumble, we came to the conclusion that the cloud should try to use `Installer::setAdditionalInstalledRepository()`.
