### ISSUE TITLE
Contao 4: is there a way to regenerate symlinks?

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-plugin#69]
When installing a Contao 3 extension in Contao 4, the composer-plugin generates symlinks from `system/modules/…` to the vendor folder of the extension (as well as symlinks in `web/` I think?).

However, what if you need to regenerate these symlinks? E.g. under windows when you move the installation or if a symlink gets lost. There is no command to do that, is there? Currently the only way I figured out is to delete all symlinks in `system/modules`, delete the whole `vendor` folder and then run `composer install` again, to force the symlinks to be regenerated. Which is rather tedious.

**Comment by aschempp** [comment]
I guess the best way would be to add a composer script (through the plugin).

**Comment by Toflar** [comment]
@fritzmg will you work on a PR here?

**Comment by fritzmg** [comment]
I'll try.

The command then also needs to be added to the `contao/installation-bundle` [here](https://github.com/contao/installation-bundle/blob/4.4.2/src/EventListener/InitializeApplicationListener.php#L34-L58), am I right? But I don't think the installation bundle should or can use Commands from and independent package..?

**Comment by Toflar** [comment]
Imho we could modify the `manager-bundle` in a way that it provides a general `contao:setup-managed-edition` command which basically does everything that currently resides in https://github.com/contao/manager-bundle/blob/master/src/Composer/ScriptHandler.php#L30.

The `ScriptHandler` would then only call `static::executeCommand('contao:setup-managed-edition', $event);`
In the `installation-bundle` we could check for `if (class_exists('Contao\ManagerBundle\ContaoManagerBundle'))` and `if` so, only execute the `contao:setup-managed-edition` command and `else` do what it does atm (= standard edition, you probably need to do other stuff for your special setup than the installation-bundle can possibly know about which would be ok because it's not managed). Wdyt @aschempp?

**Comment by fritzmg** [comment]
Yes, but where does a command from an arbitrary bundle/package come into play? May be through a custom event?

**Comment by aschempp** [comment]
@Toflar completly misunderstood the topic. It's not related to any Contao bundle at all, as this is the composer plugin for Contao 3 modules. Apparently, Composer is not triggering the install event if the package is not actually installed. Dunno if there is a *repair* event or something we could always listen to…

**Comment by Toflar** [comment]
Fixed in PR https://github.com/contao-community-alliance/composer-plugin/pull/71

**Comment by fritzmg** [comment]
Ever since this change I randomly get the error
```
  [RuntimeException]
  Could not delete /home/www/naturimgarten.at/system/modules/some_module:
```
when running a composer update. For some reason, the plugin is unable to remove the existing symlink (though user rights etc. are fine).

**Comment by Toflar** [comment]
I guess that's not related, I had this too and @aschempp fixed with https://github.com/contao-community-alliance/composer-plugin/commit/6bb098d34191fccb03579bf9ad37b14435951565, sure you are on the latest version?

**Comment by fritzmg** [comment]
> sure you are on the latest version?

Actually no - looking at the output I saw an update of the composer-plugin package in the last project where that happened.

**Comment by Toflar** [comment]
So that should be gone then :)
